filter:
  include_entities:
    - light.living_room_ceiling
    - light.living_room_hanging_lamp
    - switch.living_room_mood_lights
    - switch.living_room_studio_main
    - light.bedroom_ceiling
    - light.bedroom_lamp
    - light.kitchen_mood_lights
    - switch.vocolinc_vp2_0edaf5_4
